### ISSUE TITLE
Add more input validation for GET API

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/start.openliberty.io#164]
Add some input validation for the GET API, specially these parameters. For example, only allow `maven` and `gradle` for the Build System parameter.
- 

My psudeo code. Add a pattern to the `regexp=` field.
```
@JavaVersion @Pattern(regexp = "", message = "Java SE Version input not supported") @QueryParam("j") @Parameter(description = "Java SE Version") String javaVersion,
@QueryParam("b") @Pattern(regexp = "", message = "Build System input not supported") @Parameter(description = "Build System") BuildSystemType buildSystem,
@JakartaEEVersion @Pattern(regexp = "", message = "Java EE / Jakarta EE Version Version input not supported") @QueryParam("e") @Parameter(description = "Java EE / Jakarta EE Version") String jakartaEEVersion,
@MicroProfileVersion @Pattern(regexp = "", message = "MicroProfile Version input not supported") @QueryParam("m") @Parameter(description = "MicroProfile Version") String microProfileVersion)
```

Code lines
https://github.com/OpenLiberty/start.openliberty.io/blob/cba17e179075ac1afc1306cddc2df55ba7d45909/src/main/java/io/openliberty/website/starter/StartResource.java#L86-L89

**Comment by amyreit** [comment]
After researching the more, the Java, EE and MP parameters already have validation running on them through the io.openliberty.website.starter.validation.validator.* classes and they print out messages if the input parms are invalid. The app name and group name are also working using the @Pattern. I don't think we can use the annotation for the build system parameter because it is defined as type BuildSystemType which is an enum and therefore has to be maven or gradle. If the user tries passing anything else, the code blows up with a message which isn't great but I think does tell them which parameter is wrong.  So, I don't think there is really anything more to do for input validation. 

![Image](https://github.com/OpenLiberty/start.openliberty.io/assets/24231238/b92cd3ff-46aa-4735-aa10-461a0451447e)

**Comment by amyreit** [comment]
Okay so after talking with Kin - this is actually more than just making sure that unsupported input is denied (which it is based on the above). We also want for security and serviceability to make the API not just fail with an Error 500 if the input is bad, we need to give the user feedback on what they did wrong so they can fix it.

**Comment by natalie-bernhard** [comment]
@kinueng can you confirm if the work from #110 covers this issue as well?

**Comment by natalie-bernhard** [comment]
The work from #110 does cover this issue.  Closing this issue as completed.
