### ISSUE TITLE
Add link to https://github.com/OpenLiberty/start.openliberty.io from start.openliberty.io

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/start.openliberty.io#23]
I had to search this repo from openliberty so that I can raise an issue. There should be a link to this repo in start.openliberty.io so that end users can provide feedback to the tool.

**Comment by mbroz2** [comment]
@Emily-Jiang wouldn't this be more of an issue to be opened against start.microprofile.io?

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang wouldn't this be more of an issue to be opened against start.microprofile.io?

I meant to say start.openliberty.io. I have now corrected the typo.

**Comment by k8vance88** [comment]
Can you take a look at this @mdenby

**Comment by mbroz2** [comment]
@mdenby any update on how to expose a link to the github repo from the starter section in /start?

**Comment by mdenby** [comment]
Thinking out loud here...why would the user need to access the start.openliberty.io? Is it just open issues or to download things to begin using Open Liberty?

I'm just wondering about what section to put it in on this page and how to let the user know what it is and how to use it.

![Screen Shot 2022-01-05 at 2 47 29 PM](https://user-images.githubusercontent.com/26823018/148279554-bd7a23e6-93fe-4375-b29d-8a263d76f968.png)

**Comment by Emily-Jiang** [comment]
This issue is about putting a github icon on the page so that a user can raise new features in this tool.

**Comment by mdenby** [comment]
Doesn't this link on the support page do that? 

The start page is to get the user installing/using Open Liberty. The support page seems like the place to go if there's an issue or they need more help.

<img width="1291" alt="Screen Shot 2022-01-06 at 10 49 04 AM" src="https://user-images.githubusercontent.com/26823018/148410551-d478a133-e5ea-46a7-9682-eb4289c9c3da.png">

**Comment by mdenby** [comment]
How about adding a link with text here?

<img width="1022" alt="Screen Shot 2022-01-12 at 12 33 26 PM" src="https://user-images.githubusercontent.com/26823018/149191942-0c7e76a2-d2db-4421-8fc8-733b5194648a.png">

**Comment by Emily-Jiang** [comment]
That works. Thanks @mdenby

**Comment by Emily-Jiang** [comment]
Actually if possible, instead of saying github, just use an icon.

**Comment by mbroz2** [comment]
I think this was closed on accident; re-opening.

**Comment by mbroz2** [comment]
If we're adding the link to the text area, then I think we should avoid using icons in a sentence.
Also, if we go with this approach, I think it should read "Having trouble using the starter?  [Raise an issue.](https://github.com/OpenLiberty/start.openliberty.io/issues/new/choose)"

I think the only drawback with the proposed approach is that it makes the 'raise an issue' very prominent (instead of, for example, having it at the end of the section (like in guides) or off to the side (like in docs).  However, it does make the implementation very easy and straightforward so even if we change our minds later, practically no time was lost making this change
